# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\ui_downInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(462, 565)
        self.label_downInfo = QtWidgets.QLabel(Dialog)
        self.label_downInfo.setGeometry(QtCore.QRect(0, 50, 421, 71))
        self.label_downInfo.setObjectName("label_downInfo")
        self.btn_selectAll = QtWidgets.QPushButton(Dialog)
        self.btn_selectAll.setGeometry(QtCore.QRect(40, 510, 81, 31))
        self.btn_selectAll.setObjectName("btn_selectAll")
        self.btn_no = QtWidgets.QPushButton(Dialog)
        self.btn_no.setGeometry(QtCore.QRect(330, 510, 81, 31))
        self.btn_no.setObjectName("btn_no")
        self.list_video = QtWidgets.QListWidget(Dialog)
        self.list_video.setGeometry(QtCore.QRect(10, 130, 441, 351))
        self.list_video.setObjectName("list_video")
        self.btn_dwonSelect = QtWidgets.QPushButton(Dialog)
        self.btn_dwonSelect.setGeometry(QtCore.QRect(180, 510, 81, 31))
        self.btn_dwonSelect.setObjectName("btn_dwonSelect")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_downInfo.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">当前选择课程为:xxx</span></p><p align=\"center\"><span style=\" font-size:14pt;\">共计xx课时,是否继续下载?</span></p></body></html>"))
        self.btn_selectAll.setText(_translate("Dialog", "取消全选"))
        self.btn_no.setText(_translate("Dialog", "取消"))
        self.btn_dwonSelect.setText(_translate("Dialog", "下载已选中"))
