# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(530, 296)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 108, 60, 16))
        self.label.setObjectName("label")
        self.comb_course = QtWidgets.QComboBox(self.centralwidget)
        self.comb_course.setGeometry(QtCore.QRect(100, 104, 271, 26))
        self.comb_course.setObjectName("comb_course")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(260, 50, 113, 32))
        self.btn_login.setObjectName("btn_login")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 157, 60, 16))
        self.label_2.setObjectName("label_2")
        self.edit_savePath = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_savePath.setGeometry(QtCore.QRect(100, 154, 271, 24))
        self.edit_savePath.setObjectName("edit_savePath")
        self.btn_selectPath = QtWidgets.QPushButton(self.centralwidget)
        self.btn_selectPath.setGeometry(QtCore.QRect(390, 152, 113, 27))
        self.btn_selectPath.setObjectName("btn_selectPath")
        self.btn_download = QtWidgets.QPushButton(self.centralwidget)
        self.btn_download.setGeometry(QtCore.QRect(390, 102, 113, 27))
        self.btn_download.setObjectName("btn_download")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 59, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_user = QtWidgets.QLabel(self.centralwidget)
        self.label_user.setGeometry(QtCore.QRect(100, 59, 151, 16))
        self.label_user.setObjectName("label_user")
        self.label_progressTitle = QtWidgets.QLabel(self.centralwidget)
        self.label_progressTitle.setGeometry(QtCore.QRect(30, 241, 60, 16))
        self.label_progressTitle.setObjectName("label_progressTitle")
        self.progressBar_down = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_down.setGeometry(QtCore.QRect(100, 239, 341, 20))
        self.progressBar_down.setProperty("value", 24)
        self.progressBar_down.setObjectName("progressBar_down")
        self.label_downPercentage = QtWidgets.QLabel(self.centralwidget)
        self.label_downPercentage.setGeometry(QtCore.QRect(450, 241, 60, 16))
        self.label_downPercentage.setObjectName("label_downPercentage")
        self.label_currentTitle = QtWidgets.QLabel(self.centralwidget)
        self.label_currentTitle.setGeometry(QtCore.QRect(30, 201, 54, 12))
        self.label_currentTitle.setObjectName("label_currentTitle")
        self.label_currentDown = QtWidgets.QLabel(self.centralwidget)
        self.label_currentDown.setGeometry(QtCore.QRect(100, 200, 391, 16))
        self.label_currentDown.setObjectName("label_currentDown")
        self.btn_quit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quit.setGeometry(QtCore.QRect(390, 50, 113, 32))
        self.btn_quit.setObjectName("btn_quit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "我的课程:"))
        self.btn_login.setText(_translate("MainWindow", "登录CCtalk"))
        self.label_2.setText(_translate("MainWindow", "保存路径:"))
        self.btn_selectPath.setText(_translate("MainWindow", "选择路径"))
        self.btn_download.setText(_translate("MainWindow", "下载"))
        self.label_3.setText(_translate("MainWindow", "账号:"))
        self.label_user.setText(_translate("MainWindow", "登录后显示"))
        self.label_progressTitle.setText(_translate("MainWindow", "下载进度:"))
        self.label_downPercentage.setText(_translate("MainWindow", "30%"))
        self.label_currentTitle.setText(_translate("MainWindow", "当前下载:"))
        self.label_currentDown.setText(_translate("MainWindow", "解析中..."))
        self.btn_quit.setText(_translate("MainWindow", "退出登录"))
